name: proyecto_dam_p2
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  observable: ^0.24.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/ic_atencion.png
    - assets/img/ic_m01.png
    - assets/img/ic_m02.png
    - assets/img/ic_m03.png
    - assets/img/ic_m04.png
    - assets/img/ic_m05.png
    - assets/img/ic_m06.png
    - assets/img/ic_m07.png
    - assets/img/ic_m08.png
    - assets/img/ic_m09.png
    - assets/img/ic_m10.png
    - assets/img/ic_m11.png
    - assets/img/ic_m12.png
    - assets/img/ic_m13.png
    - assets/img/ic_m14.png
    - assets/img/ic_m15.png
    - assets/img/ic_m16.png
    - assets/img/ic_m17.png
    - assets/img/ic_m18.png
    - assets/img/ic_m19.png
    - assets/img/ic_m20.png
    - assets/img/ic_m21.png
    - assets/img/ic_m22.png
    - assets/img/ic_m23.png
    - assets/img/ic_m24.png
    - assets/img/ic_m25.png
    - assets/img/ic_m26.png
    - assets/img/ic_m27.png
    - assets/img/ic_m28.png
    - assets/img/ic_m29.png
    - assets/img/ic_m30.png
    - assets/img/ic_m31.png
    - assets/img/ic_m32.png
    - assets/img/ic_m33.png
    - assets/img/ic_m34.png
    - assets/img/ic_m35.png
    - assets/img/ic_m36.png
    - assets/img/ic_m37.png
    - assets/img/ic_m38.png
    - assets/img/ic_m39.png
    - assets/img/ic_m40.png
    - assets/img/ic_m41.png
    - assets/img/ic_m42.png
    - assets/img/ic_m43.png
    - assets/img/ic_m44.png
    - assets/img/ic_m45.png
    - assets/img/ic_m46.png
    - assets/img/ic_m47.png
    - assets/img/ic_m48.png
    - assets/img/ic_m49.png
    - assets/img/ic_m50.png
    - assets/img/ic_m51.png
    - assets/img/ic_m52.png
    - assets/img/ic_m53.png
    - assets/img/ic_m54.png
    - assets/img/ic_m55.png
    - assets/img/ic_m56.png
    - assets/img/ic_m57.png
    - assets/img/ic_m58.jpg
    - assets/img/ic_m59.png
    - assets/img/ic_m60.png
    - assets/img/ic_m61.png
    - assets/img/ic_m62.png
    - assets/img/ic_m63.jpg
    - assets/img/ic_m64.png
    - assets/img/ic_m65.png
    - assets/img/ic_m66.png
    - assets/img/ic_m67.png
    - assets/img/ic_pensamiento.png
    - assets/img/ic_per1.png
    - assets/img/ic_percepcion.png
    - assets/img/ic_aprendizaje.png
    - assets/img/ic_softlogo.png
    - assets/img/ic_uglogo.png
    - assets/img/mentalgame_icono.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
