// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVm-ejGPOBREPno8p3V_2pSfrkrERWOiE',
    appId: '1:302650977956:web:be43c214a5a0b316a90031',
    messagingSenderId: '302650977956',
    projectId: 'proyecto1dam-5d964',
    authDomain: 'proyecto1dam-5d964.firebaseapp.com',
    storageBucket: 'proyecto1dam-5d964.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC51PeN467yVAHx4r1kYjZSj8rnEH9KqOY',
    appId: '1:302650977956:android:16a2055d7f2b3d77a90031',
    messagingSenderId: '302650977956',
    projectId: 'proyecto1dam-5d964',
    storageBucket: 'proyecto1dam-5d964.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZ8i1ZvAkQS3_jy-qKsCSRrO46LC91fI',
    appId: '1:302650977956:ios:efadfefe811cfac9a90031',
    messagingSenderId: '302650977956',
    projectId: 'proyecto1dam-5d964',
    storageBucket: 'proyecto1dam-5d964.appspot.com',
    iosClientId: '302650977956-mv0lomqg7chi7obs1fthge2ef317aahc.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoDamP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZ8i1ZvAkQS3_jy-qKsCSRrO46LC91fI',
    appId: '1:302650977956:ios:efadfefe811cfac9a90031',
    messagingSenderId: '302650977956',
    projectId: 'proyecto1dam-5d964',
    storageBucket: 'proyecto1dam-5d964.appspot.com',
    iosClientId: '302650977956-mv0lomqg7chi7obs1fthge2ef317aahc.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoDamP2',
  );
}
